CFLAGS = -I ../include
LIBS = -lncurses
CC = gcc
SOURCES = main.c
OBJECTS = $(SOURCES:.c=.o)
EXECUTABLE =  ../bin/main

all: exec

debug: CFLAGS += -g3
debug: clean
debug: exec

exec: $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXECUTABLE) $(LIBS) $(CFLAGS)

.PHONY: clean
clean:
	rm $(EXECUTABLE) $(OBJECTS)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) -c $(OBJECTS) $@
